# for windows terminal inputting random charracter when tmux attached.
# https://github.com/tmux/tmux/issues/4541#issuecomment-3055148003
set -sg escape-time 500 # or set to some value larger than 10
set -g focus-events off

# 24bit color tmux 
# link : https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g mouse on

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

## select panes using opt(alt)
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
